"""added routineScoring for storing startValues

Revision ID: 379dbf8946a7
Revises: feae70b1f26b
Create Date: 2025-01-27 12:53:30.920339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379dbf8946a7'
down_revision = 'feae70b1f26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_scoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('scoring_type', sa.String(length=20), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'scoring_type', name='unique_routine_scoring')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_scoring')
    # ### end Alembic commands ###
