"""added uniqueness to routine skill w/ position

Revision ID: 5f3fb38706e8
Revises: d5df5700d7d9
Create Date: 2025-01-21 10:15:03.497181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3fb38706e8'
down_revision = 'd5df5700d7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_skills', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_routine_skill_position', ['routine_id', 'skill_id', 'position'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_skills', schema=None) as batch_op:
        batch_op.drop_constraint('unique_routine_skill_position', type_='unique')

    # ### end Alembic commands ###
