"""Delete frequency column to routine_skills

Revision ID: d5df5700d7d9
Revises: 90c91e019589
Create Date: 2025-01-20 18:26:06.917842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5df5700d7d9'
down_revision = '90c91e019589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_skills', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
