"""Added name column to routine

Revision ID: feae70b1f26b
Revises: 5f3fb38706e8
Create Date: 2025-01-23 10:46:13.334595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feae70b1f26b'
down_revision = '5f3fb38706e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
